package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import logica.Cliente;
import logica.Empleado;

/**
 *
 * @author Jonathan
 */
public class Main extends javax.swing.JFrame implements ActionListener {

    Empleado empleado = new Empleado();
    Cliente cliente = new Cliente();
    String persona="";
    String clientes="";
    public Main() {
        initComponents();
        BtnGuardarPersona.addActionListener(this);
        BtnGuardarCliente.addActionListener(this);
        BtnConsultarPersona.addActionListener(this);
        BtnConsultarCliente.addActionListener(this);
        empleado.crearArchivoPersona();
        cliente.crearArchivoCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtApellido = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtnGuardarPersona = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtCodigoCliente = new javax.swing.JTextField();
        TxtSaldoCliente = new javax.swing.JTextField();
        BtnGuardarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtPersonas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtCliente = new javax.swing.JTextArea();
        BtnConsultarPersona = new javax.swing.JButton();
        BtnConsultarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel2.setText("nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));
        jPanel1.add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 180, -1));
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, -1));

        jLabel3.setText("apeliido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel1.add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, -1));
        jPanel1.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 180, -1));
        jPanel1.add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 200, -1));

        jLabel4.setText("direccion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        BtnGuardarPersona.setText("Guardar Persona");
        jPanel1.add(BtnGuardarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel5.setText("telefono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel6.setText("Codigo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jLabel7.setText("Saldo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));
        jPanel1.add(TxtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 190, -1));
        jPanel1.add(TxtSaldoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 180, -1));

        BtnGuardarCliente.setText("Guardar Cliente");
        jPanel1.add(BtnGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        TxtPersonas.setColumns(20);
        TxtPersonas.setRows(5);
        jScrollPane1.setViewportView(TxtPersonas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 360, -1));

        TxtCliente.setColumns(20);
        TxtCliente.setRows(5);
        jScrollPane2.setViewportView(TxtCliente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 460, 390, -1));

        BtnConsultarPersona.setText("Consultar persona");
        jPanel1.add(BtnConsultarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        BtnConsultarCliente.setText("Consultar cliente");
        jPanel1.add(BtnConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultarCliente;
    private javax.swing.JButton BtnConsultarPersona;
    private javax.swing.JButton BtnGuardarCliente;
    private javax.swing.JButton BtnGuardarPersona;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextArea TxtCliente;
    private javax.swing.JTextField TxtCodigoCliente;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextArea TxtPersonas;
    private javax.swing.JTextField TxtSaldoCliente;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == BtnGuardarPersona){
            persona += TxtId.getText() +" ";
            persona += TxtNombre.getText()+" ";
            persona += TxtApellido.getText()+" ";
            persona += TxtDireccion.getText()+" ";
            persona += TxtTelefono.getText()+ "\n";
            
            empleado.Guardar(persona);
            persona="";
        }
        if(e.getSource() == BtnGuardarCliente){
            clientes += TxtId.getText() +" ";
            clientes += TxtNombre.getText()+" ";
            clientes += TxtApellido.getText()+" ";
            clientes += TxtDireccion.getText()+" ";
            clientes += TxtTelefono.getText()+ " ";
            clientes += TxtCodigoCliente.getText() +" ";
            clientes += "Q"+ TxtSaldoCliente.getText() +"\n";
            
            cliente.GuardarCliente(clientes);
            clientes="";
        }
        if(e.getSource() == BtnConsultarPersona){
            empleado.consultarPersona();
            TxtPersonas.setText(empleado.leerArchivoPersona("archivoPersona.txt"));
        }
        if(e.getSource() == BtnConsultarCliente){
            TxtCliente.setText(cliente.leerArchivoCliente("archivoCliente.txt"));
        }
    }
}
